version: '2'
services:
  colonial_static:
    image: nginx
    container_name: colonial_static
    restart: always
    volumes:
      - ./static-content:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=thenetwork"
      - "traefik.port=80"
      - "traefik.backend=colonial_static"
      - "traefik.frontend.rule=Host:colonialrevival.lib.virginia.edu"

networks:
  default:
    external:
      name: thenetwork
